### ISSUE TITLE
Solo update gives ssl error

### ISSUE THREAD

**Issue by djnugent** [3drobotics/solo-cli#13]
Stacktrace

``` bash
daniel@daniel-VirtualBox:~$ solo update solo 1.1.15
you are about to update Solo.
this preserves all your local changes to Solo, but compatibility
with newer updates is not guaranteed.
proceed to perform update? [y/N] y
checking Internet connectivity...
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/bin/solo", line 9, in <module>
    load_entry_point('soloutils==1.0.0', 'console_scripts', 'solo')()
File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/soloutils/__main__.py", line 33, in <module>
    soloutils.update.main(args)
  File "/usr/local/lib/python2.7/dist-packages/soloutils/update.py", line 144, in main
    file_loc, md5_loc = fetch(updates[-1])
  File "/usr/local/lib/python2.7/dist-packages/soloutils/update.py", line 55, in fetch
    u = requests.get(release.url, stream=True)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 471, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 579, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 430, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

**Comment by tcr3dr** [comment]
@djnugent Can you `sudo -H pip install requests[security]` (exactly like that) and retry?

**Comment by djnugent** [comment]
Still did not work

**Comment by tcr3dr** [comment]
Fixed on master by manually installing the SSL deps.
