### ISSUE TITLE
Fail to connect to internet: rpmdb

### ISSUE THREAD

**Issue by djnugent** [3drobotics/solo-cli#14]
``` bash
Lease of 10.1.50.252 obtained, lease time 3600
/etc/udhcpc.d/50default: Adding DNS 8.8.8.8
/etc/udhcpc.d/50default: Adding DNS 8.8.4.4
connecting to the internet...
rpmdb: BDB2506 file /var/lib/rpm/Packages has LSN 2/1798827, past end of log at 2/1731005
rpmdb: BDB2507 Commonly caused by moving a database from one database environment
rpmdb: BDB2508 to another without clearing the database LSNs, or by removing all of
rpmdb: BDB2509 the log files from a database environment
error: cannot open Packages(0) index: Invalid argument(22)
    DB: Berkeley DB 5.3.21: (May 11, 2012)
error: cannot open Packages database in /var/lib/rpm
Traceback (most recent call last):
  File "/usr/bin/smart", line 200, in <module>
    main(sys.argv[1:])
  File "/usr/bin/smart", line 173, in main
    exitcode = iface.run(opts.command, opts.argv)
  File "/usr/lib/python2.7/site-packages/smart/interface.py", line 53, in run
    result = _command.main(self._ctrl, opts)
  File "/usr/lib/python2.7/site-packages/smart/commands/query.py", line 160, in main
    ctrl.reloadChannels()
  File "/usr/lib/python2.7/site-packages/smart/control.py", line 412, in reloadChannels
    self._cache.load()
  File "/usr/lib/python2.7/site-packages/smart/backends/rpm/header.py", line 255, in load
    for h, offset in self.getHeaders(prog):
  File "/usr/lib/python2.7/site-packages/smart/backends/rpm/header.py", line 628, in getHeaders
    mi = getTS().dbMatch()
TypeError: rpmdb open failed
rpmdb: BDB2506 file /var/lib/rpm/Packages has LSN 2/1798827, past end of log at 2/1731005
rpmdb: BDB2507 Commonly caused by moving a database from one database environment
rpmdb: BDB2508 to another without clearing the database LSNs, or by removing all of
rpmdb: BDB2509 the log files from a database environment
error: cannot open Packages(0) index: Invalid argument(22)
    DB: Berkeley DB 5.3.21: (May 11, 2012)
error: cannot open Packages database in /var/lib/rpm
rpmdb: BDB2506 file /var/lib/rpm/Packages has LSN 2/1798827, past end of log at 2/1731005
rpmdb: BDB2507 Commonly caused by moving a database from one database environment
rpmdb: BDB2508 to another without clearing the database LSNs, or by removing all of
rpmdb: BDB2509 the log files from a database environment
error: cannot open Packages database in /var/lib/rpm
insmod: ERROR: could not load module /lib/modules/3.10.17-rt12-*/kernel/net/ipv4/netfilter/iptable_filter.ko: No such file or directory
iptables v1.4.19.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.4.19.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
```

**Comment by djnugent** [comment]
`rpm --rebuilddb` did not solve the problem. I updated to 1.1.16, bypassed the version check, and it worked.

**Comment by djnugent** [comment]
Issue is for outdated version
