### ISSUE TITLE
Solo info fails

### ISSUE THREAD

**Issue by djnugent** [3drobotics/solo-cli#17]
Fails if no gimbal is attach... I think. I'll look more into it if I have time today.

``` bash
daniel@daniel-VirtualBox:~$ solo info
connecting to Solo and the Controller...
Traceback (most recent call last):
  File "/usr/local/bin/solo", line 9, in <module>
    load_entry_point('soloutils==1.0.0', 'console_scripts', 'solo')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/soloutils/__main__.py", line 37, in <module>
    soloutils.info.main(args)
  File "/usr/local/lib/python2.7/dist-packages/soloutils/info.py", line 18, in main
    data['gimbal'] = soloutils.gimbal_versions(solo)
  File "/usr/local/lib/python2.7/dist-packages/soloutils/__init__.py", line 115, in gimbal_versions
    version, = gimbal_str.strip().split()
ValueError: need more than 0 values to unpack
```

**Comment by tcr3dr** [comment]
@djnugent Can you try again using master? I made a fix for the gimbal issue.

**Comment by tcr3dr** [comment]
Confirmed working. Apparently there's a spec for this stuff!
