### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by HalfdanJ** [3drobotics/solo-cli#36]
When I try to use the CLI tool to connect to the solo, i get the following error: 

```
connecting to Solo and the Controller...
Traceback (most recent call last):
  File "/usr/local/bin/solo", line 9, in <module>
    load_entry_point('solo-cli==1.1.1', 'console_scripts', 'solo')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/soloutils/__main__.py", line 39, in <module>
    soloutils.info.main(args)
  File "/usr/local/lib/python2.7/site-packages/soloutils/info.py", line 12, in main
    controller = soloutils.connect_controller(await=True)
  File "/usr/local/lib/python2.7/site-packages/soloutils/__init__.py", line 56, in connect_controller
    return _connect('10.1.1.1', await=await, silent=silent)
  File "/usr/local/lib/python2.7/site-packages/soloutils/__init__.py", line 25, in _connect
    client.load_system_host_keys()
  File "/usr/local/lib/python2.7/site-packages/paramiko/client.py", line 101, in load_system_host_keys
    self._system_host_keys.load(filename)
  File "/usr/local/lib/python2.7/site-packages/paramiko/hostkeys.py", line 101, in load
    e = HostKeyEntry.from_line(line, lineno)
  File "/usr/local/lib/python2.7/site-packages/paramiko/hostkeys.py", line 341, in from_line
    raise InvalidHostKey(line, e)
paramiko.hostkeys.InvalidHostKey: ('raspberry ssh-rsa XXXXXXNzaC1yc2EAAAADAQABAAABAQDHHcLeLQUpmcNce+KK5p+aMb2KU8KFW5R/xJLwZmgGtwbejHE+QFP37Yx9wLEk1KzXn+0bnTaUUb78NCKFzL2uY/raBKlm4VaxhyF5DSWowGnUw7OudiT/rmYcX38wfLbkNbYm12RpD4Ss/94/EVZShFZN4F455mPO+NbieFoqXp4+f71W6qk4FgTjNbllrWSr2DUt00ca6pNO1ciCI1rEEehOh5Iv70Oos26hNxzuFGYzRjoLG4eeo66VAkCFWwDJa5M62OUeQgTPoo2JR0L/5nyzVUnvHIHfe/mNGEAkwTvGn9o3ruGmISLIpYIFNAz+RrQf6iVjAyffRIXT5W0x192.168.1.133 ssh-rsa XXXXXXXzaC1yc2EAAAADAQABAAABAQCrmdolKsuxoVHZKQbOTDJQ/aBuMLQta5d9iPsIoKdY/K9WLWSBNDHogSZB2QAIVG/+TyIX6Ejce6MM1/pLycS7SDUe9otKN3LpcNDZDnM+Sy6FROYboVG2UvkfR7pREeWTf2FAGjv4bUs5VoyAgHQMj3C+oyagIHbM1xIp+XFyxbIxdYyiHdVYxkfSR+uL3VT/EZjy9QGjlSm9LrkYyEtZt+zPJToCeP1U5PwTvEvR85BAtMBjNlhx+blNMy6B/VHWkSev0trrTRQHM7y7JAHyeQP/BypYTtF/UI9G3GbSoleVAq3aM0jDZAEKZCBGuqW3crGZdj/YgMzMbIQjWrFN', Error('Incorrect padding',))
```

(i've scrambled the key) 

Seems like a ssh problem? Am I missing a setup step?

**Comment by pgreyson** [comment]
I ran into the same issue. Fixed by removing the line(s) for that host from ~/.ssh/known_hosts. There are a couple threads about parmiko throwing errors on "invalid" known_hosts entries but possibly the problem will recur if you ssh to the same host again? Anyway it's a workaround.
