### ISSUE TITLE
solo flash drone/controller doesn't work on Windows

### ISSUE THREAD

**Issue by hamishwillee** [3drobotics/solo-cli#41]
I tried a number of alternatives but except for getting the list, all fail similarly:

```
D:\Github\solodevguide\examples\helloworld>solo flash both latest --clean
you are about to flash Solo and the Controller.
by specifying --clean, you will REMOVE ALL LOCAL CHANGES to Solo.
proceed to perform update? [y/N] y

checking Internet connectivity...
Traceback (most recent call last):
  File "D:\apps\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\Scripts\solo-script.py", line 9, in <module>
    load_entry_point('solo-cli==1.1.2', 'console_scripts', 'solo')()
  File "D:\apps\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\pkg_resources\__init__.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "D:\apps\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\pkg_resources\__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "D:\apps\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\pkg_resources\__init__.py", line 2380, in load
    return self.resolve()
  File "D:\apps\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\pkg_resources\__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "D:\apps\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\solo_cli-1.1.2-py2.7.egg\soloutils\__main__.py", line 37, in <module>
    soloutils.flash.main(args)
  File "D:\apps\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\solo_cli-1.1.2-py2.7.egg\soloutils\flash.py", line 321, in main
    drone_file, drone_md5 = download_firmware('drone', version)
  File "D:\apps\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\solo_cli-1.1.2-py2.7.egg\soloutils\flash.py", line 259, in download_firmware
    return fetch(updates[-1])
  File "D:\apps\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\solo_cli-1.1.2-py2.7.egg\soloutils\flash.py", line 56, in fetch
    f = open('/tmp/' + file_name, 'wb')
IOError: [Errno 2] No such file or directory: u'/tmp/solo_2.0.0.tar.gz'
```

**Comment by johnwalz97** [comment]
Anybody who has this issue can now get around it by using the Windows Subsystem for Linux application that is part of the Anniversary Update developer tools. Then you can just follow the linux instructions which work well.
