### ISSUE TITLE
Can not install Command Line Tools

### ISSUE THREAD

**Issue by fenyi2016** [3drobotics/solo-cli#49]
Hi there, 
When I use $ sudo pip install https://github.com/3drobotics/solo-cli/archive/master.zip --no-cache-dir
to install cli, this error came out:

Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)

How can I solve this? I'm using Ubuntu14.04 and Python2.7.6. 
Thanks!

**Comment by Helibank** [comment]
Hi,

You can run this first sudo pip install --upgrade setuptools
Then, run sudo -H pip install git+https://github.com/3drobotics/solo-cli

After these two steps, you can type solo, it works for me.
